# Generated by Django 3.1.6 on 2021-02-14 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('email', models.EmailField(max_length=50, verbose_name='E-mail')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата Регистрации')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователей',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.TextField(blank=True, max_length=200, verbose_name='Сообщение')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата Отправки сообщения')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.user', verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
