# Generated by Django 3.1.6 on 2021-02-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210214_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='messages',
            field=models.TextField(blank=True, verbose_name='Сообщение'),
        ),
    ]
